# Generated by Django 3.0.3 on 2020-02-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=1000)),
                ('project_status', models.CharField(max_length=50)),
                ('github_link', models.CharField(max_length=100)),
                ('circuit_link', models.CharField(max_length=100)),
                ('project_leader', models.CharField(max_length=50)),
                ('project_members', models.CharField(max_length=1000)),
                ('project_date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
